/**
 * 
 */
package org.owasp.webscarab.jdbc;

import java.sql.SQLException;

import org.owasp.webscarab.dao.BlobDao;
import org.owasp.webscarab.dao.UrlDao;
import org.owasp.webscarab.jdbc.VersionDao;
import org.springframework.jdbc.core.JdbcTemplate;

/**
 * @author rdawes
 * 
 */
public class HsqlJdbcConversationDao extends AbstractJdbcConversationDao {

    public HsqlJdbcConversationDao(Integer session, UrlDao urlDao,
            VersionDao versionDao, HeadersDao headersDao, BlobDao blobDao) {
        super(session, urlDao, versionDao, headersDao, blobDao);
    }

    /*
     * (non-Javadoc)
     * 
     * @see org.owasp.webscarab.jdbc.AbstractJdbcUrlDao#createTables()
     */
    @Override
    protected void createTables() throws SQLException {
        JdbcTemplate template = new JdbcTemplate(this.getDataSource());

        template.execute("CREATE TABLE methods (" + "id INT NOT NULL IDENTITY,"
                + "method VARCHAR(16))");
        template
                .execute("CREATE CACHED TABLE conversations ("
                        + "id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY, "
                        + "session INT NOT NULL," + "date TIMESTAMP NOT NULL,"
                        + "request_method INT NOT NULL,"
                        + "request_url INT NOT NULL,"
                        + "request_version INT NOT NULL,"
                        + "request_content_checksum CHAR(32),"
                        + "response_version INT NOT NULL,"
                        + "response_status CHAR(3) NOT NULL,"
                        + "response_message INT NOT NULL,"
                        + "response_content_checksum CHAR(32),"
                        + "plugin INT NOT NULL)");
        template.execute("CREATE CACHED TABLE messages ("
                + "id INT NOT NULL IDENTITY," + "message VARCHAR(256))");
        template.execute("CREATE TABLE versions ("
                + "id INT NOT NULL IDENTITY," + "version CHAR(8) NOT NULL)");
        template.execute("CREATE CACHED TABLE descriptions ("
                + "id INT NOT NULL," + "description VARCHAR(256))");
    }

    /*
     * (non-Javadoc)
     * 
     * @see org.owasp.webscarab.jdbc.AbstractJdbcUrlDao#getIdentityQuery()
     */
    @Override
    protected String getIdentityQuery() {
        return "CALL IDENTITY()";
    }

}
